name: CI - Build and Test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/phrase-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.102"

      - name: Restore dependencies
        run: dotnet restore

      - name: Install the SonarScanner for .NET tool
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool
        
      - name: SonarCloud begin
        run: >
          dotnet sonarscanner begin
          /o:"darksoft"
          /k:"darksoft_the-wall"
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
          /d:sonar.cs.opencover.reportsPaths=coverage-report/opencover.xml

      - name: Build
        run: dotnet build --no-restore

      - name: Run tests with coverage
        run: >
          dotnet test
          --collect:"XPlat Code Coverage"
          --results-directory ./TestResults

      - name: Convert coverage to OpenCover
        run: |
          reportgenerator \
          -reports:TestResults/**/coverage.cobertura.xml \
          -targetdir:coverage-report \
          -reporttypes:OpenCover

      - name: SonarCloud end
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
