name: CI - Build and Test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

env:
  SONAR_CLOUD_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.102"

      - name: Restore dependencies
        run: dotnet restore backend/phrase-service

      - name: Install the SonarScanner for .NET tool
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Install dotnet-coverage
        run: dotnet tool install --global dotnet-coverage
        
      - name: SonarCloud begin
        run: >
          dotnet sonarscanner begin
          /o:"darksoft"
          /k:"darksoft_the-wall"
          /d:sonar.token="$SONAR_CLOUD_TOKEN"
          /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml

      - name: Build
        run: dotnet build backend/phrase-service --no-restore

      - name: Run tests with coverage
        run: dotnet-coverage collect "dotnet test backend/phrase-service" -f xml -o "coverage.xml"

      - name: SonarCloud end
        run: dotnet sonarscanner end /d:sonar.token="$SONAR_CLOUD_TOKEN"
